'use client'
import { useTranslation as useLocaleText } from '@/i18n/provider'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Bus, MapPin, Radio, Users, CheckCircle2, AlertTriangle, Send, Play, Square, ShieldCheck } from 'lucide-react'
import { useTranslation } from '@/i18n/provider'
import { api, Child, Person, Stop, useAccount, Workspace, Empty, NoticeBar, formatDate } from '@/components/transport/shared'
import { nextAttendanceAction } from '@/lib/transport'
type RecordItem = { id: string; studentId: string; action: string; timestamp: string; stopId?: string }
type CrewData = { bus: { id: string; plateNumber: string; busNumber?: string; capacity: number; driver?: Person; maintainer?: Person; route?: { id: string; name: string; stops: Stop[] } } | null; activeTrip: { id: string; date: string; attendances: RecordItem[] } | null; students: Child[] }
export default function DriverDashboard() {
 const {tx:translateUi}=useLocaleText()

  const me = useAccount('DRIVER'), { tx, locale } = useTranslation()
  const [data, setData] = useState<CrewData>({ bus: null, activeTrip: null, students: [] }), [error, setError] = useState(''), [busy, setBusy] = useState(false), [query, setQuery] = useState(''), [stopId, setStopId] = useState('')
  const [history,setHistory]=useState<{id:string;date:string;routeName:string;attendance:{studentName:string;action:string;timestamp:string}[]}[]>([])
  const [broadcast, setBroadcast] = useState(''), [broadcastType, setBroadcastType] = useState('TRAFFIC'), [sharing, setSharing] = useState(false)
  const [confirm, setConfirm] = useState<{ child: Child; action: string } | null>(null), [atStop, setAtStop] = useState(false)
  const watch = useRef<number | null>(null), position = useRef<{ latitude: number; longitude: number; timestamp: number } | null>(null), lastSent = useRef(0), loading = useRef(false)
  const load = useCallback(async () => { if (!me || loading.current) return; loading.current = true; try { const [status,records]=await Promise.all([api('/api/driver/status'),api('/api/trips/history')]);setData(status);setHistory(records.trips || []) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load data') } finally { loading.current = false } }, [me])
  useEffect(() => { void load(); const timer = setInterval(load, 10000); return () => clearInterval(timer) }, [load])
  const stopSharing = useCallback(() => { if (watch.current !== null) navigator.geolocation.clearWatch(watch.current); watch.current = null; setSharing(false) }, [])
  useEffect(() => () => { if (watch.current !== null) navigator.geolocation.clearWatch(watch.current) }, [])
  useEffect(() => { if (!data.activeTrip) stopSharing() }, [data.activeTrip, stopSharing])
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); try { await work() } catch (e) { setError(e instanceof Error ? e.message : 'Network error') } finally { setBusy(false) } }
  const startSharing = () => {
    if (!navigator.geolocation || !window.isSecureContext) { setError('Location permission is required on HTTPS.'); return }
    stopSharing()
    watch.current = navigator.geolocation.watchPosition(p => {
      position.current = { latitude: p.coords.latitude, longitude: p.coords.longitude, timestamp: p.timestamp }
      setSharing(true)
      if (Date.now() - lastSent.current >= 8000) { lastSent.current = Date.now(); void api('/api/location', position.current).catch(e => setError(e.message)) }
    }, () => { setError('Location permission is required on HTTPS.'); stopSharing() }, { enableHighAccuracy: true, maximumAge: 5000, timeout: 20000 })
  }
  const records = data.activeTrip?.attendances || []
  const status = (id: string) => { const actions = records.filter(r => r.studentId === id).map(r => r.action); return actions.includes('ABSENT') ? 'Absent' : actions.includes('DROPPED_OFF') ? 'Dropped off' : actions.includes('PICKED_UP') ? 'On board' : 'Waiting' }
  const counts = ['Waiting', 'On board', 'Dropped off', 'Absent'].map(label => ({ label, count: data.students.filter(s => status(s.id) === label).length }))
  const roster = data.students.filter(s => s.name.toLowerCase().includes(query.toLowerCase()) && (!stopId || s.pickupStopId === stopId || s.dropoffStopId === stopId))
  const selectedStop = confirm?.action === 'DROPPED_OFF' ? confirm.child.dropoffStop : confirm?.child.pickupStop
  return <Workspace me={me} title={translateUi("Crew workspace")}><NoticeBar message={error} retry={load}/>{!data.bus ? <Empty text="Ask your School Admin to assign a bus, route and students."/> : <>
    <section className="crew-route-card"><div className="bus-icon"><Bus size={34}/></div><div><p className="eyebrow">{tx("Today's route")}</p><h2 data-no-translate>{data.bus.route?.name || tx('School assignment pending')}</h2><p data-no-translate>{data.bus.busNumber || data.bus.plateNumber} · {data.bus.plateNumber}</p></div><div className="crew-trip-controls">{!data.activeTrip ? <button className="transport-primary" disabled={busy || !data.bus.route} onClick={() => run(async () => { await api('/api/trips', { busId: data.bus!.id, routeId: data.bus!.route?.id }); await load(); startSharing(); setError('Trip started') })}><Play size={18}/>{tx('Start trip')}</button> : <button className="transport-primary" disabled={busy} onClick={() => run(async () => { await api(`/api/trips/${data.activeTrip!.id}`, { status: 'TRIP_COMPLETED' }, 'PATCH'); stopSharing(); await load(); setError('Trip completed') })}><CheckCircle2 size={18}/>{tx('Complete trip')}</button>}</div></section>
    <div className="crew-details journey-card"><span>{tx('Driver')}: <strong data-no-translate>{data.bus.driver?.name || '—'}</strong></span><span>{tx('Maintainer')}: <strong data-no-translate>{data.bus.maintainer?.name || '—'}</strong></span><span>{tx('Seats')}: {data.bus.capacity}</span>{data.activeTrip && <time>{formatDate(data.activeTrip.date, locale)}</time>}</div>
    <div className="attendance-counts">{counts.map(c => <div key={c.label}><span>{tx(c.label)}</span><strong>{c.count}</strong></div>)}</div>
    <div className="journey-grid crew-grid"><section><div className="section-title"><h2><Users size={22}/>{tx('Student attendance')}</h2></div><div className="roster-filters"><input placeholder={tx('Search students')} value={query} onChange={e => setQuery(e.target.value)}/><select value={stopId} onChange={e => setStopId(e.target.value)}><option value="">{tx('All stops')}</option>{data.bus.route?.stops.map(s => <option value={s.id} key={s.id} data-no-translate>{s.order}. {s.name}</option>)}</select></div>
      {!data.activeTrip && <NoticeBar message="Start a trip to record attendance."/>}{!roster.length && <Empty text="No students assigned"/>}
      {roster.map(child => { const action = nextAttendanceAction(records.filter(r => r.studentId === child.id).map(r => r.action)); const last = records.filter(r => r.studentId === child.id).at(-1); return <article className="student-attendance-card" key={child.id}><div className="bus-title"><div className="child-avatar" data-no-translate>{child.name.slice(0, 1)}</div><div><h3 data-no-translate>{child.name}</h3><p data-no-translate>{child.grade} · {child.studentCode}</p></div><span className={`status-pill ${status(child.id) === 'On board' ? 'green' : ''}`}>{tx(status(child.id))}</span></div><div className="stop-pair"><p><MapPin size={16}/>{tx('Pickup stop')}: <strong data-no-translate>{child.pickupStop?.name || '—'}</strong></p><p><MapPin size={16}/>{tx('Drop-off stop')}: <strong data-no-translate>{child.dropoffStop?.name || '—'}</strong></p></div>{last && <time>{formatDate(last.timestamp, locale)}</time>}<div className="attendance-actions">{action && <button className="transport-primary" disabled={busy || !data.activeTrip} onClick={() => { setConfirm({ child, action }); setAtStop(false) }}>{tx(action === 'PICKED_UP' ? 'Confirm boarding' : 'Confirm drop-off')}</button>}{action === 'PICKED_UP' && <button className="transport-secondary" disabled={busy || !data.activeTrip} onClick={() => { setConfirm({ child, action: 'ABSENT' }); setAtStop(false) }}>{tx('Mark absent')}</button>}</div></article> })}
      </section><aside><section className="journey-card"><h2><Radio size={20}/>{tx('GPS sharing')}</h2><p>{tx(sharing ? 'Sharing location' : 'Share bus GPS')}</p><button className="transport-secondary" disabled={!data.activeTrip} onClick={sharing ? stopSharing : startSharing}>{sharing ? <Square size={16}/> : <Radio size={16}/>} {tx(sharing ? 'Stop sharing' : 'Share bus GPS')}</button></section><section className="journey-card"><h2>{tx('Route stops')}</h2><ol className="stop-timeline">{data.bus.route?.stops.map(stop => <li key={stop.id}><span>{stop.order}</span><strong data-no-translate>{stop.name}</strong></li>)}</ol></section><section className="journey-card"><h2>{tx('Broadcast to parents')}</h2><form onSubmit={e => { e.preventDefault(); void run(async () => { await api('/api/driver/broadcast', { tripId: data.activeTrip?.id, type: broadcastType, message: broadcast }); setBroadcast(''); setError('Broadcast sent') }) }}><select value={broadcastType} onChange={e => setBroadcastType(e.target.value)}>{[['TRAFFIC','Traffic'],['BUS_DELAYED','Delay'],['BREAKDOWN','Breakdown'],['OTHER','Other']].map(([value,label]) => <option value={value} key={value}>{tx(label)}</option>)}</select><textarea required maxLength={500} placeholder={tx('Type a message')} value={broadcast} onChange={e => setBroadcast(e.target.value)}/><button className="transport-primary" disabled={busy || !data.activeTrip}><Send size={18}/>{tx('Send broadcast')}</button></form></section><button className="emergency-button" disabled={busy} onClick={() => { if (window.confirm(tx('Send an emergency alert to the school?'))) void run(async () => { await api('/api/emergency', {}); setError('Emergency alert sent') }) }}><AlertTriangle/>{tx('Emergency SOS')}</button></aside></div>
    <section className="journey-card"><h2>{tx('Recent attendance')}</h2>{!history.length && <Empty text="No attendance records"/>}{history.slice(0,5).map(trip=><details key={trip.id} className="history-entry"><summary><span data-no-translate>{trip.routeName}</span> · {formatDate(trip.date,locale)}</summary>{trip.attendance.map((a,i)=><div className="attendance-history" key={i}><strong data-no-translate>{a.studentName}</strong><span>{tx(a.action==='PICKED_UP'?'Boarded':a.action==='DROPPED_OFF'?'Dropped off':'Absent')}</span><time>{formatDate(a.timestamp,locale)}</time></div>)}</details>)}</section>
    {confirm && <div className="transport-modal-backdrop"><section className="transport-modal" role="dialog" aria-modal="true" aria-labelledby="attendance-confirm"><ShieldCheck size={34}/><h2 id="attendance-confirm">{tx(confirm.action === 'ABSENT' ? 'Mark absent' : confirm.action === 'PICKED_UP' ? 'Confirm boarding' : 'Confirm drop-off')}</h2><h3 data-no-translate>{confirm.child.name}</h3><p data-no-translate>{selectedStop?.name}</p><p>{tx('Parents receive a notification after confirmation.')}</p>{confirm.action !== 'ABSENT' && <label className="checkbox-row"><input type="checkbox" checked={atStop} onChange={e => setAtStop(e.target.checked)}/>{tx('The bus is at the assigned stop.')}</label>}<div className="attendance-actions"><button className="transport-secondary" onClick={() => setConfirm(null)}>{tx('Cancel')}</button><button className="transport-primary" disabled={busy || confirm.action !== 'ABSENT' && !atStop} onClick={() => run(async () => { const gps = position.current && Date.now() - position.current.timestamp < 60000 ? position.current : {}; await api('/api/attendance', { tripId: data.activeTrip!.id, studentId: confirm.child.id, action: confirm.action, stopId: selectedStop?.id, confirmStop: atStop, ...gps }); setConfirm(null); await load() })}>{tx('Confirm')}</button></div></section></div>}
  </>}</Workspace>
}
